# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nom_categ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='nom_clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='nom_estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Impacto')),
            ],
        ),
        migrations.CreateModel(
            name='nom_lineamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lineamiento')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tipo_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tipo_salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo salida')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Funciones')),
            ],
        ),
        migrations.CreateModel(
            name='publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Titulo')),
                ('nombrerevista', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre de la Revista')),
                ('isbn', models.CharField(blank=True, max_length=256, null=True, verbose_name='ISBN')),
                ('nroautores', models.CharField(blank=True, max_length=256, null=True, verbose_name='Cantidad de Autores')),
                ('anno', models.DateField(verbose_name='Registrado')),
                ('autorprincipal', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
                ('tipo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.tipo_publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Titulo')),
                ('linea_investig', models.CharField(blank=True, max_length=256, null=True, verbose_name='Linea de Investigacion')),
                ('fecha_inicio', models.DateField(blank=True, max_length=256, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_entrada', models.DateField(blank=True, max_length=256, null=True, verbose_name='Fecha de Entrada')),
                ('fecha_terminacion', models.DateField(blank=True, max_length=256, null=True, verbose_name='Fecha de Terminacion')),
                ('causa_detenido', models.CharField(blank=True, max_length=256, null=True, verbose_name='Causa de Terminacion')),
                ('categ', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_categ')),
                ('clasificacion', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_clasificacion')),
                ('estado', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_estado')),
                ('impacto', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_impacto')),
                ('lineamiento', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_lineamiento')),
                ('persona', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
                ('tipo_proyecto', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_tipo_proyecto')),
                ('tipo_salida', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.nom_tipo_salida')),
                ('unidad', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
    ]
