# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='No Mesa')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=20148, null=True, verbose_name='Comentario')),
                ('pedido', models.DateTimeField(blank=True, max_length=30, null=True, verbose_name='Momento')),
            ],
        ),
        migrations.CreateModel(
            name='tipomovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cantidad')),
                ('importe', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Importe')),
                ('pcosto', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Precio de Costo')),
                ('actualizacion', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado')),
                ('mesa', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribucion.mesa')),
                ('pedido', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribucion.pedido')),
                ('tipomovimiento', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribucion.tipomovimiento')),
                ('unidad', models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
    ]
