# Generated by Django 4.1.1 on 2022-11-29 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        ('tareas', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deficiencia')),
                ('observaciones', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('fechafin', models.DateTimeField(null=True, verbose_name='Fecha de cierre de la deficiencia')),
                ('puntoaspecto', models.CharField(blank=True, max_length=250, null=True, verbose_name='punto de aspecto')),
                ('activo', models.BooleanField(blank=True, max_length=250, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Aspecto_Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto', models.CharField(max_length=250, null=True, unique=True, verbose_name='Tipo de Estado')),
                ('activo', models.BooleanField(blank=True, max_length=250, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Estado_Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de Estado')),
                ('activo', models.BooleanField(blank=True, max_length=250, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Tipo_Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo de Tarea')),
                ('activo', models.BooleanField(blank=True, max_length=250, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 5, 25, 23, 921114), verbose_name='Fecha de la visita')),
                ('visitado', models.CharField(blank=True, max_length=250, null=True, verbose_name='Visitado')),
                ('activo', models.BooleanField(blank=True, max_length=250, verbose_name='Estado')),
                ('participantes', models.ManyToManyField(blank=True, max_length=250, to='rrhh.trabajador')),
                ('tipo', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.nom_tipo_visita')),
                ('unidad', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='unidad.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='deficienciasXtareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deficiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspeccion.deficiencia')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficient', to='tareas.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='deficiencia',
            name='aspecto',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.nom_aspecto_deficiencia'),
        ),
        migrations.AddField(
            model_name='deficiencia',
            name='estado',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.nom_estado_deficiencia'),
        ),
        migrations.AddField(
            model_name='deficiencia',
            name='tarea',
            field=models.ManyToManyField(through='inspeccion.deficienciasXtareas', to='tareas.tarea'),
        ),
        migrations.AddField(
            model_name='deficiencia',
            name='visita',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deficiencias', to='inspeccion.visita'),
        ),
    ]
