# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion
import unidad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.FloatField(blank=True, verbose_name='Presupuesto Inicial de Unidad')),
                ('cantidad_actual', models.FloatField(blank=True, verbose_name='Presupuesto Actual de Unidad')),
                ('actualizacion', models.DateField(auto_now_add=True, verbose_name=unidad.models.Unidad)),
                ('unidad', models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Servicio_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='Número de Orden')),
                ('tipo_servicio', models.CharField(choices=[('compra', 'Compra'), ('mantenimiento', 'Mantenimiento'), ('dictamen', 'Dictamen Técnico'), ('reparacion', 'Reparación'), ('montaje', 'Montaje'), ('modernizacion', 'Modernización')], max_length=256, null=True, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('importe', models.FloatField(blank=True, verbose_name='Importe')),
                ('actualizacion', models.DateField(auto_now_add=True, verbose_name=unidad.models.Unidad)),
                ('unidad', models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
    ]
