# Generated by Django 4.1.1 on 2022-11-29 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nom_Categoria_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Tarea')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Clasificacion_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Tarea')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Estado_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Estado')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Frecuencia_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Frecuencia')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Prioridad_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Prioridad')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
                ('freg', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fini', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 5, 25, 23, 789461), verbose_name='Fecha de Inicio')),
                ('ffin', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 5, 25, 23, 789461), verbose_name='Fecha de Finalizacion')),
                ('responsable', models.CharField(blank=True, max_length=256, null=True, verbose_name='Responsable')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
                ('categoria', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.nom_categoria_tarea')),
                ('clasificacion', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.nom_clasificacion_tarea')),
                ('estado', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.nom_estado_tarea')),
                ('participantes', models.ManyToManyField(max_length=256, to='rrhh.trabajador')),
                ('prioridad', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.nom_prioridad_tarea')),
            ],
        ),
    ]
