# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rrhh.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.CharField(blank=True, max_length=256, null=True, verbose_name='pc')),
                ('ip', models.CharField(blank=True, max_length=256, null=True, verbose_name='ip')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Cargo_Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Funciones')),
                ('resposabilidad', models.TextField(blank=True, max_length=256, null=True, verbose_name='Responsabilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Habilidad_Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(blank=True, max_length=256, null=True, verbose_name='Habilidad')),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Titulo_Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Categoria Profecional')),
                ('especialidad', models.TextField(blank=True, max_length=256, null=True, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=250)),
                ('unidad', models.CharField(blank=True, max_length=250)),
                ('departamento', models.CharField(blank=True, max_length=250)),
                ('trabajador', models.CharField(blank=True, max_length=250)),
                ('accion', models.CharField(blank=True, max_length=250)),
                ('numaccion', models.IntegerField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el: ')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, null=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=rrhh.models.Trabajador.get_upload_img_name)),
                ('carne', models.CharField(blank=True, max_length=256, null=True, verbose_name='Carne de Identidad')),
                ('correo', models.EmailField(max_length=256, null=True, verbose_name='Correo electronico')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Direccion')),
                ('graduado', models.CharField(blank=True, max_length=256, null=True, verbose_name='Graduado de ')),
                ('telefono', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefono')),
                ('registro', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('estado', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
                ('cargo', models.ManyToManyField(to='rrhh.nom_cargo_trabajador')),
                ('municipio', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_municipio')),
                ('plaza_ocupa', models.OneToOneField(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_plaza', to='unidad.plaza_departamento')),
                ('titulo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.nom_titulo_trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='registromaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el: ')),
                ('estado', models.CharField(blank=True, max_length=256, verbose_name='Estado')),
                ('pc', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador', models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='rrhh.trabajador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
