# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nom_ap_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ap_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_board_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_bocinas_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_camara_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_camara_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_cddvd_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_cddvd_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_cddvd_utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_chasis_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_chasis_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_fuente_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_fuente_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_hdd_capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_hdd_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_hdd_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_impresora_interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interface')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_impresora_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_impresora_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_modem_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_modem_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_monitor_dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimension')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_monitor_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_monitor_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_procesador_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_procesador_velocidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ram_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ram_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ram_velocidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_raton_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_scanner_dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimension')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_scanner_interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interface')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_scanner_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_scanner_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_stick_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_stick_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_switch_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_switch_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_teclado_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_teclado_raton_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tipo_pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de PC')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tred_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tred_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tred_velocidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tsonido_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tsonido_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tvideo_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_tvideo_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ups_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='nom_ups_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
            ],
        ),
        migrations.CreateModel(
            name='pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la Maquina')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.estado', verbose_name='Estado')),
                ('responsable', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='so',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sistema Operativo')),
            ],
        ),
        migrations.CreateModel(
            name='ups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('ups_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ups_marca')),
                ('ups_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ups_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='tvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidad')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('ftvideo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tvideo_tipo', verbose_name='Tipo de tarjeta de video')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('tvideo_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tvideo_marca', verbose_name='Marca de la tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='tsonido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacidad')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('tsonido_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tsonido_marca', verbose_name='Marca')),
                ('tsonido_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tsonido_tipo', verbose_name='Tipo de tarjeta de Sonido')),
            ],
        ),
        migrations.CreateModel(
            name='tred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('tred_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tred_marca')),
                ('tred_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tred_tipo')),
                ('tred_velocidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tred_velocidad')),
            ],
        ),
        migrations.CreateModel(
            name='teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('teclado_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_teclado_marca', verbose_name='Marca del Teclado')),
                ('teclado_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_teclado_raton_tipo', verbose_name='Tipo de Teclado')),
            ],
        ),
        migrations.CreateModel(
            name='switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidad')),
                ('num_puertos', models.CharField(blank=True, max_length=50, null=True)),
                ('reponsable', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
                ('switch_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_switch_marca')),
                ('switch_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_switch_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='stick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidad')),
                ('reponsable', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
                ('stick_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_stick_marca')),
                ('stick_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_stick_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('scanner_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_scanner_dimension')),
                ('scanner_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_scanner_interface')),
                ('scanner_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_scanner_marca')),
                ('scanner_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_scanner_tipo')),
            ],
        ),
        migrations.CreateModel(
            name='raton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('bocinas_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_bocinas_marca')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('ram_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ram_marca', verbose_name='Marca de la RAM')),
                ('ram_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ram_tipo', verbose_name='Tipo de RAM')),
                ('ram_velocidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ram_velocidad', verbose_name='Velocidad')),
            ],
        ),
        migrations.CreateModel(
            name='procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
                ('procesador_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_procesador_marca', verbose_name='Marca del Micro')),
                ('procesador_socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_socket', verbose_name='Socket del Micro')),
                ('procesador_velocidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_procesador_velocidad', verbose_name='Velocidad')),
            ],
        ),
        migrations.AddField(
            model_name='pc',
            name='so',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.so', verbose_name='Sistema Operativo'),
        ),
        migrations.AddField(
            model_name='pc',
            name='tipo_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_tipo_pc', verbose_name='Tipo de Estacion'),
        ),
        migrations.CreateModel(
            name='monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('monitor_dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_monitor_dimension', verbose_name='Dimensiones')),
                ('monitor_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_monitor_marca', verbose_name='Marca del Monitor')),
                ('monitor_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_monitor_tipo', verbose_name='Tipo')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('modem_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_modem_marca')),
                ('modem_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_modem_tipo')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('impresora_inteface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_impresora_interface', verbose_name='Enlace con la PC')),
                ('impresora_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_impresora_marca', verbose_name='Marca de la Impresora')),
                ('impresora_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_impresora_tipo', verbose_name='Tipo')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='hdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('hdd_capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_hdd_capacidad', verbose_name='Capacidad en GB')),
                ('hdd_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_hdd_marca', verbose_name='Marca')),
                ('hdd_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_hdd_tipo', verbose_name='Tipo de Disco Duro')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Potencia')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_fuente_marca', verbose_name='Marca')),
                ('fuente_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_fuente_tipo', verbose_name='Tipo de fuente')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='chasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('chasis_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_chasis_marca', verbose_name='Marca del Chasis')),
                ('chasis_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_chasis_tipo', verbose_name='Tipo de Chasis')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='cddvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('cddvd_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_cddvd_marca', verbose_name='Marca')),
                ('cddvd_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_cddvd_tipo', verbose_name='Tipo de Dispositivo')),
                ('cddvd_utilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_cddvd_utilidad', verbose_name='Utilidad')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('camara_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_camara_marca')),
                ('camara_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_camara_tipo')),
                ('reponsable', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='board_pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('board_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_board_marca', verbose_name='Marca de la Board')),
                ('board_socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_socket', verbose_name='Socket de la Board')),
                ('pc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.pc')),
            ],
        ),
        migrations.CreateModel(
            name='ap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, max_length=50, verbose_name='Activado')),
                ('inventario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Inventario')),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidad')),
                ('ap_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ap_marca')),
                ('ap_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamiento.nom_ap_tipo')),
                ('reponsable', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
    ]
