# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        ('transporte', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapa_movil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chapa del Movil')),
                ('marca_movil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Marca del Movil')),
            ],
        ),
        migrations.CreateModel(
            name='nom_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=256, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='unidad_radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='estaciones_repetidoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo')),
                ('ubicacion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ubicacion de la estacion')),
                ('estado', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Obsoleto', 'Obsoleto'), ('Sin Funcionar', 'Sin Funcionar')], default='Funcionando', max_length=256, verbose_name='Estado de la estacion repetidora')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.nom_marca')),
            ],
        ),
        migrations.CreateModel(
            name='estaciones_portatiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicativo', models.CharField(max_length=128, unique=True, verbose_name='Indicativo')),
                ('modelo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo')),
                ('estado', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Obsoleto', 'Obsoleto'), ('Sin Funcionar', 'Sin Funcionar')], default='Funcionando', max_length=256, verbose_name='Estado de la estacion portatil')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.nom_marca')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='estaciones_movil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicativo', models.CharField(max_length=128, unique=True, verbose_name='Indicativo')),
                ('modelo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo')),
                ('estado', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Obsoleto', 'Obsoleto'), ('Sin Funcionar', 'Sin Funcionar')], default='Funcionando', max_length=256, verbose_name='Estado de la estacion movil')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.nom_marca')),
                ('movil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.parque')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidad.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='estaciones_fijas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicativo', models.CharField(max_length=128, unique=True, verbose_name='Indicativo')),
                ('modelo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo')),
                ('estado', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Obsoleto', 'Obsoleto'), ('Sin Funcionar', 'Sin Funcionar')], default='Funcionando', max_length=256, verbose_name='Estado de la estacion fija')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.nom_marca')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidad.departamento')),
            ],
        ),
    ]
