# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(max_length=256, verbose_name='Comision')),
                ('comentarioe', models.CharField(max_length=256, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='estomatologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoe', models.CharField(max_length=256, verbose_name='Estado Estomatologico')),
                ('comentarioe', models.CharField(max_length=256, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadof', models.CharField(max_length=256, verbose_name='Estado de Familiar')),
                ('comentariof', models.CharField(max_length=256, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='llamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='nom_categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrec', models.CharField(max_length=256, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='nom_especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombree', models.CharField(max_length=256, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='recluta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre')),
                ('ci', models.CharField(blank=True, max_length=11, null=True, verbose_name='Carnet de Identidad')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('c_estudios', models.CharField(blank=True, max_length=150, null=True, verbose_name='Centro de Estudios')),
                ('c_trabajo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Centro de Trabajo')),
                ('area', models.CharField(blank=True, max_length=150, null=True, verbose_name='Area de Salud')),
                ('centro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Centro Medico')),
                ('antecedentes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Antecedentes Patologicos Faniliares')),
                ('documentacion', models.BooleanField(blank=True, default=False, max_length=256, verbose_name='Documentacion Pendiente')),
                ('investigacion', models.BooleanField(blank=True, default=False, max_length=256, verbose_name='Investigacion Pendiente')),
                ('registrado', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('estomat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.estomatologia')),
                ('familiaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.familia')),
                ('llamadoo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.llamado')),
                ('municipio', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_municipio')),
            ],
        ),
        migrations.CreateModel(
            name='salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(max_length=256, verbose_name='Estado de Salud')),
                ('comentarios', models.CharField(max_length=256, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=256, null=True, verbose_name='Comentario')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('confirmacion', models.BooleanField(blank=True, default=False, max_length=256, verbose_name='Confirmar Reclutamiento')),
                ('registrado', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.nom_categoria')),
                ('comision', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.comision')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.nom_especialidad')),
                ('recluta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.recluta')),
            ],
        ),
        migrations.AddField(
            model_name='recluta',
            name='saludd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclutamiento.salud'),
        ),
    ]
