# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion
import unidad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefono')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Codigo')),
                ('municipio', models.CharField(blank=True, max_length=256, null=True, verbose_name='Municipio')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Nivel_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nivel de Subordinacion de la Unidad')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Perfil_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(blank=True, max_length=256, null=True, verbose_name='Perfil de la Unidad')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_formales', models.TextField(blank=True, max_length=256, null=True, verbose_name='Requisitos formales')),
                ('salario', models.FloatField(blank=True, max_length=256, null=True, verbose_name='Salario Basico')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(blank=True, max_length=256, null=True, verbose_name='Provincia')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Tipo_Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoplaza', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Plaza')),
            ],
        ),
        migrations.CreateModel(
            name='Nom_Tipo_Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Unidad')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_unidad_organizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo de Unidad Organizativa')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='unidad_organizativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre de la Unidad Organizativa')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Codigo unico de la Unidad')),
                ('nombre', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre de la Unidad')),
                ('direccion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=256, null=True, verbose_name='Telefono de la Recepcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=unidad.models.Unidad.get_upload_img_name)),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
                ('municipio', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_municipio')),
                ('nivel', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_nivel_unidad')),
                ('perfil', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_perfil_unidad')),
                ('subordinacion', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinados', to='unidad.unidad')),
                ('tipo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_tipo_unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Plaza_Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=256, null=True, verbose_name='Estado de la plaza')),
                ('activo', models.BooleanField(blank=True, max_length=256, verbose_name='Estado')),
                ('departamento', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaza_departamento', to='unidad.departamento')),
                ('plaza', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_plaza')),
            ],
        ),
        migrations.AddField(
            model_name='nom_plaza',
            name='plaza',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_tipo_plaza'),
        ),
        migrations.AddField(
            model_name='nom_municipio',
            name='provincia',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.nom_provincia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='nombre',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad_organizativa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='tipouorganizativa',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.tipo_unidad_organizativa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='unidad.unidad'),
        ),
    ]
