# Generated by Django 4.1.1 on 2022-11-29 05:25

import activos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=activos.models.activos.get_upload_img_name)),
                ('inventario', models.IntegerField(blank=True, null=True, verbose_name='Numero de Inventario')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('importe_activo', models.IntegerField(blank=True, null=True, verbose_name='Importe')),
            ],
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre el Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, verbose_name='Numero')),
                ('nombre', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='submayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submayor', models.IntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='subgrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Codigo')),
                ('descripcion', models.TextField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
                ('numero', models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='orden_activos_fijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('doc_alta', models.IntegerField(blank=True, null=True, verbose_name='Numero de Doc. de Alta')),
                ('importe', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Importe')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de Baja')),
                ('doc_baja', models.IntegerField(blank=True, null=True, verbose_name='Numero de Doc. de Baja')),
                ('activos', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.activos')),
            ],
        ),
        migrations.AddField(
            model_name='activos',
            name='cnmb',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.subgrupos'),
        ),
        migrations.AddField(
            model_name='activos',
            name='dpto',
            field=models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='unidad.departamento'),
        ),
        migrations.AddField(
            model_name='activos',
            name='nombre',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.articulo'),
        ),
        migrations.AddField(
            model_name='activos',
            name='subMayor',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='activos.submayor'),
        ),
    ]
