# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.db import migrations, models
import django.db.models.deletion
import transporte.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bateria', models.CharField(blank=True, max_length=256, null=True, verbose_name='Bateria')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(blank=True, max_length=256, null=True, verbose_name='Combustible')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementos', models.CharField(blank=True, max_length=256, null=True, verbose_name='Elementos')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='estadooperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadooperativo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Estado operativo')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='estadotecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadotecnico', models.CharField(blank=True, max_length=256, null=True, verbose_name='Estado tecnico')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Funcion')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=256, null=True, verbose_name='Marca')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='neumatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neumatico', models.CharField(blank=True, max_length=256, null=True, verbose_name='Neumatico')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tipo')),
                ('activo', models.BooleanField(blank=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='parque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=256, null=True, verbose_name='Matricula')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=transporte.models.parque.get_upload_img_name)),
                ('serie', models.CharField(blank=True, max_length=256, null=True, verbose_name='Serie')),
                ('motor', models.CharField(blank=True, max_length=256, null=True, verbose_name='Motor')),
                ('ficav', models.DateTimeField(blank=True, null=True, verbose_name='FICAV')),
                ('circulacion', models.DateTimeField(blank=True, null=True, verbose_name='Lic. de Circulacion')),
                ('operativa', models.DateTimeField(blank=True, null=True, verbose_name='Lic. Operativa')),
                ('modelo', models.CharField(blank=True, max_length=256, null=True, verbose_name='Modelo')),
                ('comentario', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Observaciones')),
                ('bateria', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.bateria')),
                ('combustible', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.combustible')),
                ('demanda', models.ManyToManyField(blank=True, max_length=256, to='transporte.demanda')),
                ('estadooperativo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.estadooperativo')),
                ('estadotecnico', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.estadotecnico')),
                ('funcion', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.funcion')),
                ('marca', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.marca')),
                ('neumatico', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.neumatico')),
                ('tipo', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.tipo')),
                ('unidad', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
    ]
