# Generated by Django 4.1.1 on 2022-11-29 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=256, null=True, verbose_name='Categoria')),
                ('descripcion', models.TextField(blank=True, max_length=256, null=True, verbose_name='Descripcion')),
                ('estado', models.BooleanField(max_length=256, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=256, null=True, verbose_name='Asunto ')),
                ('texto', models.TextField(blank=True, max_length=256, null=True, verbose_name='Texto')),
                ('respuesta', models.TextField(blank=True, max_length=256, null=True, verbose_name='Respuesta')),
                ('estado', models.CharField(blank=True, max_length=256, null=True, verbose_name='estado')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('registro', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('ip', models.CharField(blank=True, max_length=256, null=True, verbose_name='Direccion IP')),
                ('categoria', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to='mensajes.categoria')),
                ('destinatario', models.ManyToManyField(blank=True, null=True, to='rrhh.trabajador')),
                ('remitente', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mensaje_leido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.mensaje')),
                ('trabajador', models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='eliminar_destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.CharField(blank=True, max_length=256, null=True, verbose_name='estado')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.mensaje')),
                ('trabajador', models.ForeignKey(blank=True, max_length=256, on_delete=django.db.models.deletion.CASCADE, to='rrhh.trabajador')),
            ],
        ),
    ]
